FROM node:18-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    libcurl4 \
    ca-certificates \
    openssl \
    curl \
    gnupg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=test

CMD ["npm", "test"]
